// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "breez-sdk-liquid-nwc.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "BreezSdkLiquidNwcSpec.h"

@interface BreezSdkLiquidNwc : NSObject <NativeBreezSdkLiquidNwcSpec>
#else
#import <React/RCTBridgeModule.h>

@interface BreezSdkLiquidNwc : NSObject <RCTBridgeModule>
#endif

@end