#ifndef BREEZTECH_BREEZSDKLIQUIDREACTNATIVE_H
#define BREEZTECH_BREEZSDKLIQUIDREACTNATIVE_H
// Generated by uniffi-bindgen-react-native
#include <cstdint>
#include <jsi/jsi.h>
#include <ReactCommon/CallInvoker.h>

namespace breeztech_breezsdkliquidreactnative {
  using namespace facebook;

  uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker);
  uint8_t cleanupRustCrate(jsi::Runtime &runtime);
}

#endif /* BREEZTECH_BREEZSDKLIQUIDREACTNATIVE_H */