// Generated by uniffi-bindgen-react-native
#include "breeztech-react-native-breez-sdk-liquid.h"
#include "generated/breez_sdk_liquid.hpp"

namespace breeztech_reactnativebreezsdkliquid {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeBreezSdkLiquid::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}