// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "breeztech-react-native-breez-sdk-liquid.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "BreezSdkLiquidReactNativeSpec.h"

@interface ReactNativeBreezSdkLiquid : NSObject <NativeReactNativeBreezSdkLiquidSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ReactNativeBreezSdkLiquid : NSObject <RCTBridgeModule>
#endif

@end