// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Bindings for `src/flutter_breez_liquid.h`.
///
/// Regenerate bindings with `flutter pub run ffigen --config ffigen.yaml`.
///
class FlutterBreezLiquidBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  FlutterBreezLiquidBindings(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  FlutterBreezLiquidBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>('store_dart_post_cobject');
  late final _store_dart_post_cobject =
      _store_dart_post_cobjectPtr.asFunction<void Function(DartPostCObjectFnType)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_backup(
    int port_,
    int that,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_backup(
      port_,
      that,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_backupPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
          'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_backup');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_backup =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_backupPtr
          .asFunction<void Function(int, int)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_get_info(
    int port_,
    int that,
    ffi.Pointer<wire_cst_get_info_request> req,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_get_info(
      port_,
      that,
      req,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_get_infoPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_get_info_request>)>>(
      'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_get_info');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_get_info =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_get_infoPtr
          .asFunction<void Function(int, int, ffi.Pointer<wire_cst_get_info_request>)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_list_payments(
    int port_,
    int that,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_list_payments(
      port_,
      that,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_list_paymentsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
          'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_list_payments');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_list_payments =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_list_paymentsPtr
          .asFunction<void Function(int, int)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_receive_payment(
    int port_,
    int that,
    ffi.Pointer<wire_cst_prepare_receive_request> req,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_receive_payment(
      port_,
      that,
      req,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_receive_paymentPtr =
      _lookup<
              ffi.NativeFunction<
                  ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_prepare_receive_request>)>>(
          'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_receive_payment');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_receive_payment =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_receive_paymentPtr
          .asFunction<void Function(int, int, ffi.Pointer<wire_cst_prepare_receive_request>)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_send_payment(
    int port_,
    int that,
    ffi.Pointer<wire_cst_prepare_send_request> req,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_send_payment(
      port_,
      that,
      req,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_send_paymentPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_prepare_send_request>)>>(
      'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_send_payment');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_send_payment =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_prepare_send_paymentPtr
          .asFunction<void Function(int, int, ffi.Pointer<wire_cst_prepare_send_request>)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_receive_payment(
    int port_,
    int that,
    ffi.Pointer<wire_cst_prepare_receive_response> req,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_receive_payment(
      port_,
      that,
      req,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_receive_paymentPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_prepare_receive_response>)>>(
      'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_receive_payment');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_receive_payment =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_receive_paymentPtr
          .asFunction<void Function(int, int, ffi.Pointer<wire_cst_prepare_receive_response>)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_restore(
    int port_,
    int that,
    ffi.Pointer<wire_cst_restore_request> req,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_restore(
      port_,
      that,
      req,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_restorePtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_restore_request>)>>(
      'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_restore');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_restore =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_restorePtr
          .asFunction<void Function(int, int, ffi.Pointer<wire_cst_restore_request>)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_send_payment(
    int port_,
    int that,
    ffi.Pointer<wire_cst_prepare_send_response> req,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_send_payment(
      port_,
      that,
      req,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_send_paymentPtr = _lookup<
          ffi.NativeFunction<
              ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Pointer<wire_cst_prepare_send_response>)>>(
      'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_send_payment');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_send_payment =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_send_paymentPtr
          .asFunction<void Function(int, int, ffi.Pointer<wire_cst_prepare_send_response>)>();

  void frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_sync(
    int port_,
    int that,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_sync(
      port_,
      that,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_syncPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
          'frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_sync');
  late final _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_sync =
      _frbgen_breez_liquid_wire__crate__bindings__BindingLiquidSdk_syncPtr
          .asFunction<void Function(int, int)>();

  void frbgen_breez_liquid_wire__crate__bindings__connect(
    int port_,
    ffi.Pointer<wire_cst_connect_request> req,
  ) {
    return _frbgen_breez_liquid_wire__crate__bindings__connect(
      port_,
      req,
    );
  }

  late final _frbgen_breez_liquid_wire__crate__bindings__connectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_connect_request>)>>(
          'frbgen_breez_liquid_wire__crate__bindings__connect');
  late final _frbgen_breez_liquid_wire__crate__bindings__connect =
      _frbgen_breez_liquid_wire__crate__bindings__connectPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_connect_request>)>();

  void
      frbgen_breez_liquid_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdk(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _frbgen_breez_liquid_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdk(
      ptr,
    );
  }

  late final _frbgen_breez_liquid_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdkPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_breez_liquid_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdk');
  late final _frbgen_breez_liquid_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdk =
      _frbgen_breez_liquid_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdkPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      frbgen_breez_liquid_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdk(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _frbgen_breez_liquid_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdk(
      ptr,
    );
  }

  late final _frbgen_breez_liquid_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdkPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_breez_liquid_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdk');
  late final _frbgen_breez_liquid_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdk =
      _frbgen_breez_liquid_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBindingLiquidSdkPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<wire_cst_connect_request> frbgen_breez_liquid_cst_new_box_autoadd_connect_request() {
    return _frbgen_breez_liquid_cst_new_box_autoadd_connect_request();
  }

  late final _frbgen_breez_liquid_cst_new_box_autoadd_connect_requestPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_connect_request> Function()>>(
          'frbgen_breez_liquid_cst_new_box_autoadd_connect_request');
  late final _frbgen_breez_liquid_cst_new_box_autoadd_connect_request =
      _frbgen_breez_liquid_cst_new_box_autoadd_connect_requestPtr
          .asFunction<ffi.Pointer<wire_cst_connect_request> Function()>();

  ffi.Pointer<wire_cst_get_info_request> frbgen_breez_liquid_cst_new_box_autoadd_get_info_request() {
    return _frbgen_breez_liquid_cst_new_box_autoadd_get_info_request();
  }

  late final _frbgen_breez_liquid_cst_new_box_autoadd_get_info_requestPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_get_info_request> Function()>>(
          'frbgen_breez_liquid_cst_new_box_autoadd_get_info_request');
  late final _frbgen_breez_liquid_cst_new_box_autoadd_get_info_request =
      _frbgen_breez_liquid_cst_new_box_autoadd_get_info_requestPtr
          .asFunction<ffi.Pointer<wire_cst_get_info_request> Function()>();

  ffi.Pointer<wire_cst_prepare_receive_request>
      frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_request() {
    return _frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_request();
  }

  late final _frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_requestPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_prepare_receive_request> Function()>>(
          'frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_request');
  late final _frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_request =
      _frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_requestPtr
          .asFunction<ffi.Pointer<wire_cst_prepare_receive_request> Function()>();

  ffi.Pointer<wire_cst_prepare_receive_response>
      frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_response() {
    return _frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_response();
  }

  late final _frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_responsePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_prepare_receive_response> Function()>>(
          'frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_response');
  late final _frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_response =
      _frbgen_breez_liquid_cst_new_box_autoadd_prepare_receive_responsePtr
          .asFunction<ffi.Pointer<wire_cst_prepare_receive_response> Function()>();

  ffi.Pointer<wire_cst_prepare_send_request> frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_request() {
    return _frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_request();
  }

  late final _frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_requestPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_prepare_send_request> Function()>>(
          'frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_request');
  late final _frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_request =
      _frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_requestPtr
          .asFunction<ffi.Pointer<wire_cst_prepare_send_request> Function()>();

  ffi.Pointer<wire_cst_prepare_send_response>
      frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_response() {
    return _frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_response();
  }

  late final _frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_responsePtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_prepare_send_response> Function()>>(
          'frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_response');
  late final _frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_response =
      _frbgen_breez_liquid_cst_new_box_autoadd_prepare_send_responsePtr
          .asFunction<ffi.Pointer<wire_cst_prepare_send_response> Function()>();

  ffi.Pointer<wire_cst_restore_request> frbgen_breez_liquid_cst_new_box_autoadd_restore_request() {
    return _frbgen_breez_liquid_cst_new_box_autoadd_restore_request();
  }

  late final _frbgen_breez_liquid_cst_new_box_autoadd_restore_requestPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_restore_request> Function()>>(
          'frbgen_breez_liquid_cst_new_box_autoadd_restore_request');
  late final _frbgen_breez_liquid_cst_new_box_autoadd_restore_request =
      _frbgen_breez_liquid_cst_new_box_autoadd_restore_requestPtr
          .asFunction<ffi.Pointer<wire_cst_restore_request> Function()>();

  ffi.Pointer<ffi.Uint64> frbgen_breez_liquid_cst_new_box_autoadd_u_64(
    int value,
  ) {
    return _frbgen_breez_liquid_cst_new_box_autoadd_u_64(
      value,
    );
  }

  late final _frbgen_breez_liquid_cst_new_box_autoadd_u_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint64> Function(ffi.Uint64)>>(
          'frbgen_breez_liquid_cst_new_box_autoadd_u_64');
  late final _frbgen_breez_liquid_cst_new_box_autoadd_u_64 =
      _frbgen_breez_liquid_cst_new_box_autoadd_u_64Ptr.asFunction<ffi.Pointer<ffi.Uint64> Function(int)>();

  ffi.Pointer<wire_cst_list_payment> frbgen_breez_liquid_cst_new_list_payment(
    int len,
  ) {
    return _frbgen_breez_liquid_cst_new_list_payment(
      len,
    );
  }

  late final _frbgen_breez_liquid_cst_new_list_paymentPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_payment> Function(ffi.Int32)>>(
          'frbgen_breez_liquid_cst_new_list_payment');
  late final _frbgen_breez_liquid_cst_new_list_payment = _frbgen_breez_liquid_cst_new_list_paymentPtr
      .asFunction<ffi.Pointer<wire_cst_list_payment> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> frbgen_breez_liquid_cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _frbgen_breez_liquid_cst_new_list_prim_u_8_strict(
      len,
    );
  }

  late final _frbgen_breez_liquid_cst_new_list_prim_u_8_strictPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)>>(
          'frbgen_breez_liquid_cst_new_list_prim_u_8_strict');
  late final _frbgen_breez_liquid_cst_new_list_prim_u_8_strict =
      _frbgen_breez_liquid_cst_new_list_prim_u_8_strictPtr
          .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>('dummy_method_to_enforce_bundling');
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

final class DartCObject extends ffi.Opaque {}

final class WireSyncRust2DartSse extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPort = ffi.Int64;
typedef DartDartPort = int;

final class _Dart_Handle extends ffi.Opaque {}

final class wire_cst_get_info_request extends ffi.Struct {
  @ffi.Bool()
  external bool with_scan;
}

final class wire_cst_prepare_receive_request extends ffi.Struct {
  @ffi.Uint64()
  external int payer_amount_sat;
}

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_prepare_send_request extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> invoice;
}

final class wire_cst_prepare_receive_response extends ffi.Struct {
  @ffi.Uint64()
  external int payer_amount_sat;

  @ffi.Uint64()
  external int fees_sat;
}

final class wire_cst_restore_request extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> backup_path;
}

final class wire_cst_prepare_send_response extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> invoice;

  @ffi.Uint64()
  external int fees_sat;
}

final class wire_cst_connect_request extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> mnemonic;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> data_dir;

  @ffi.Int32()
  external int network;
}

final class wire_cst_payment extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> tx_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> swap_id;

  @ffi.Uint32()
  external int timestamp;

  @ffi.Uint64()
  external int amount_sat;

  external ffi.Pointer<ffi.Uint64> fees_sat;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> preimage;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> refund_tx_id;

  external ffi.Pointer<ffi.Uint64> refund_tx_amount_sat;

  @ffi.Int32()
  external int payment_type;

  @ffi.Int32()
  external int status;
}

final class wire_cst_list_payment extends ffi.Struct {
  external ffi.Pointer<wire_cst_payment> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_get_info_response extends ffi.Struct {
  @ffi.Uint64()
  external int balance_sat;

  @ffi.Uint64()
  external int pending_send_sat;

  @ffi.Uint64()
  external int pending_receive_sat;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> pubkey;
}

final class wire_cst_LiquidSdkError_Generic extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> err;
}

final class LiquidSdkErrorKind extends ffi.Union {
  external wire_cst_LiquidSdkError_Generic Generic;
}

final class wire_cst_liquid_sdk_error extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external LiquidSdkErrorKind kind;
}

final class wire_cst_PaymentError_Generic extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> err;
}

final class wire_cst_PaymentError_LwkError extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> err;
}

final class wire_cst_PaymentError_Refunded extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> err;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> refund_tx_id;
}

final class wire_cst_PaymentError_SendError extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> err;
}

final class wire_cst_PaymentError_SignerError extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> err;
}

final class PaymentErrorKind extends ffi.Union {
  external wire_cst_PaymentError_Generic Generic;

  external wire_cst_PaymentError_LwkError LwkError;

  external wire_cst_PaymentError_Refunded Refunded;

  external wire_cst_PaymentError_SendError SendError;

  external wire_cst_PaymentError_SignerError SignerError;
}

final class wire_cst_payment_error extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external PaymentErrorKind kind;
}

final class wire_cst_receive_payment_response extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> invoice;
}

final class wire_cst_send_payment_response extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> txid;
}

const double LIQUID_CLAIM_TX_FEERATE_MSAT = 100.0;
